# Generated by Django 5.0 on 2023-12-16 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="Question")),
                (
                    "author_name",
                    models.CharField(max_length=64, verbose_name="Author name"),
                ),
                ("author_url", models.URLField(blank=True, verbose_name="Author url")),
                (
                    "question_url",
                    models.URLField(blank=True, verbose_name="Question url"),
                ),
                ("asked_at", models.DateTimeField(verbose_name="Question asked at")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
