# Generated by Django 5.0 on 2023-12-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_user_id",
                    models.CharField(max_length=255, verbose_name="Telegram user id"),
                ),
                (
                    "telegram_username",
                    models.CharField(max_length=64, verbose_name="Telegram username"),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(
                        db_index=True, max_length=16, verbose_name="Telegram chat id"
                    ),
                ),
                (
                    "ozon_seller_id",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Ozon seller id"
                    ),
                ),
                (
                    "ozon_seller_url",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Ozon seller url"
                    ),
                ),
                (
                    "ozon_client_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Ozon Client Id"
                    ),
                ),
                (
                    "ozon_api_key",
                    models.CharField(
                        blank=True, max_length=36, verbose_name="Ozon API Key"
                    ),
                ),
                ("ozon_credentials_added_at", models.DateTimeField(blank=True)),
                (
                    "wildberries_seller_id",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Wildberries seller id"
                    ),
                ),
                (
                    "wildberries_seller_url",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        verbose_name="Wildberries seller url",
                    ),
                ),
                (
                    "wildberries_api_key",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Wildberries api key"
                    ),
                ),
                ("wildberries_api_key_added_at", models.DateTimeField(blank=True)),
                (
                    "yandex_market_seller_id",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        verbose_name="Yandex Market seller id",
                    ),
                ),
                (
                    "yandex_market_seller_url",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        verbose_name="Yandex Market seller url",
                    ),
                ),
                (
                    "yandex_market_api_key",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Yandex Market API Key"
                    ),
                ),
                ("yandex_market_api_key_added_at", models.DateTimeField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
