# Generated by Django 5.0 on 2023-12-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="ozon_api_key",
            field=models.CharField(
                blank=True, max_length=36, null=True, verbose_name="Ozon API Key"
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="ozon_client_id",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Ozon Client Id"
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="ozon_credentials_added_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="seller",
            name="ozon_seller_id",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Ozon seller id"
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="ozon_seller_url",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Ozon seller url"
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="wildberries_api_key",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="Wildberries api key",
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="wildberries_api_key_added_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="seller",
            name="wildberries_seller_id",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                verbose_name="Wildberries seller id",
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="wildberries_seller_url",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="Wildberries seller url",
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="yandex_market_api_key",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="Yandex Market API Key",
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="yandex_market_api_key_added_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="seller",
            name="yandex_market_seller_id",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                verbose_name="Yandex Market seller id",
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="yandex_market_seller_url",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="Yandex Market seller url",
            ),
        ),
    ]
