# Generated by Django 5.0 on 2023-12-16 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0002_alter_seller_ozon_api_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="ozon_api_key",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="ozon_client_id",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="ozon_credentials_added_at",
        ),
        migrations.CreateModel(
            name="OzonCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(max_length=64, verbose_name="Ozon Client Id"),
                ),
                (
                    "api_key",
                    models.CharField(max_length=36, verbose_name="Ozon API Key"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sellers.seller"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WildberriesCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(max_length=36, verbose_name="Wildberries API Key"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sellers.seller"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YandexMarketCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        max_length=36, verbose_name="Yandex Market API Key"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sellers.seller"
                    ),
                ),
            ],
        ),
    ]
