# Generated by Django 5.0 on 2023-12-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0003_remove_seller_ozon_api_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="wildberries_api_key",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="wildberries_api_key_added_at",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="yandex_market_api_key",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="yandex_market_api_key_added_at",
        ),
    ]
