# Generated by Django 5.0 on 2023-12-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0004_remove_seller_wildberries_api_key_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OzonCredentials",
            new_name="OzonCredential",
        ),
        migrations.RenameModel(
            old_name="WildberriesCredentials",
            new_name="WildberriesCredential",
        ),
        migrations.RenameModel(
            old_name="YandexMarketCredentials",
            new_name="YandexMarketCredential",
        ),
    ]
