# Generated by Django 5.0 on 2023-12-16 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sellers", "0005_rename_ozoncredentials_ozoncredential_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ozoncredential",
            name="seller",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="sellers.seller"
            ),
        ),
        migrations.AlterField(
            model_name="wildberriescredential",
            name="seller",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="sellers.seller"
            ),
        ),
        migrations.AlterField(
            model_name="yandexmarketcredential",
            name="seller",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="sellers.seller"
            ),
        ),
    ]
