# Generated by Django 5.0 on 2023-12-16 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_user_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Telegram user id"
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Telegram username"
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=16,
                        verbose_name="Telegram chat id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sellers.seller"
                    ),
                ),
            ],
        ),
    ]
